server:
  port: 8083

auth:
  service:
    url:
      http://localhsot:8084

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8084
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: api-docs-auth-service
          uri: http://auth-service:8084
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs



        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
