services:
  analytics-service:
    container_name: analytics-service
    image: mantichanouar/analytics-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
networks:
  internal:
    name: internal