version: '3.8'

services:
  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=patient-db
    volumes:
      - ../docker-volumes/patient-service-db:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    container_name: patient-service
    image: mantichanouar/patient-service
    ports:
      - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/patient-db
        - SPRING_DATASOURCE_USERNAME=user           
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_SQL_INIT_MODE=always
        - BILLING_SERVICE_ADDRESS=billing-service
        - BILLING_SERVICE_GRPC_PORT=9001
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    depends_on:
      - patient-service-db

networks:
  internal:
    name: internal
