services:
  billing-service:
    container_name: billing-service
    image: mantichanouar/billing-service
    ports:
      - 8081:8081
      - 9001:9001
    networks:
      - internal
networks:
  internal:
    name: internal
